### ISSUE TITLE
Rename to avoid confusion

### ISSUE THREAD

**Issue by lemmy** [tlaplus/tla_python#1]
Should this repo be renamed to e.g. "pytla" to avoid confusion?

**Comment by johnyf** [comment]
I am thinking of renaming this repository to `tla_python`. A motivation is to place TLA+ related Python utilities in a package named `tlapy` (a development snapshot can be found at: https://github.com/johnyf/tlapy), in analogy to `numpy`, `pluspy`, `scipy`. The current package would be focused on parsing, and additional material developed in other packages.

**Comment by johnyf** [comment]
This repository has been renamed to `tla_python`.
